First commit from Madiyar. Added teacher service
Cemil5/school_project pull request #1
Opened 2022-09-03 01:13 UTC by madiyard

Couldn't find Gadir and Natalie to review

2022-09-04 14:52 UTC, Cemil5 commented on src/main/java/com/cydeo/service/TeacherService.java
> +
Please finish this method

2022-09-04 14:52 UTC, Cemil5 commented on src/main/java/com/cydeo/service/TeacherService.java
> +    public void update(Teacher teacher) {
Please finish this method

2022-09-04 14:52 UTC, Cemil5 commented on src/main/java/com/cydeo/service/TeacherService.java
> +
Please finish this method

2022-09-04 14:53 UTC, Cemil5 requested changes
Please finish last three methods

2022-09-05 17:30 UTC, gibrahimov requested changes
we are still waiting for methods got updated.

2022-09-07 16:42 UTC, Cemil5 approved these changes

2022-09-07 16:44 UTC, Cemil5 approved these changes

2022-09-07 16:46 UTC, khashayarshayesteh approved these changes

2022-09-07 16:58 UTC, gibrahimov approved these changes
((

2022-09-07 16:58 UTC, merged