Us 2 course service nc ig
Cemil5/school_project pull request #2
Opened 2022-09-05 17:25 UTC by gibrahimov

please review the codes in CourseService class

2022-09-06 04:54 UTC, Cemil5 requested changes
Please, delete stream part of deleteById method and then update your pull request. Other parts seems good.

2022-09-06 04:54 UTC, Cemil5 commented on src/main/java/com/cydeo/service/CourseService.java
> +        Database.courseList.stream()
No need for stream here. Since you don't assign the result, it doesn't change anything. If you want to assign it to Database.courseList then you should change filter condition and also terminal operation.
removeIf method is enough.

2022-09-07 06:06 UTC, Cemil5 approved these changes
Thanks for your efforts.

2022-09-07 16:26 UTC, Burulai001 approved these changes

2022-09-07 16:26 UTC, Burulai001 commented
Accepted

2022-09-07 16:32 UTC, khashayarshayesteh approved these changes

2022-09-07 16:32 UTC, merged